version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8100:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - postgres_host=postgres
      - postgres_user='${postgres_user}'
      - postgres_pass='${postgres_user}'
      - postgres_db=graph-node
      - ipfs='ipfs:5001'
      - ethereum='mainnet:https://lb.nodies.app/v1/${KEY}'
      - GRAPH_LOG=error
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    expose:
      - 5432/tcp
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: 8934jhilsdjfashjkidfah
      POSTGRES_PASSWORD: 39asdlofhasdf98iyhdasf
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
