version: '3'
services:
  graph-node:
    container_name: graph-node
    image: graphprotocol/graph-node
    ports:
      - '8100:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: ${postgres_user}
      postgres_pass: ${postgres_pass}
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://lb.nodies.app/v1/${KEY}'
      GRAPH_LOG: warning
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:v0.10.0
    expose:
      - 5001/tcp
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    container_name: postgres
    image: postgres:14
    expose:
      - 5432/tcp
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_pass}
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
